<a href="https://colab.research.google.com/github/aradeyal/machine_learning/blob/main/targil_numpy_students.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

#fill in whats missing to get  print- 6

6


In [ ]:
#תרגיל 1
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])

6


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ',#fill in whats missing to get  print - Last element from 2nd dim:  10

Last element from 2nd dim:  10


In [ ]:
#תרגיל 2
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ',arr[1][-1])

Last element from 2nd dim:  10


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

#fill in whats missing to get  print [2 3 4 5]

[2 3 4 5]


In [ ]:
#תרגיל 3
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

#fill in whats missing to get  print [1 2 3 4]

[1 2 3 4]


In [ ]:
#תרגיל 4
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [ ]:


arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)
print('shape of array :', arr.shape)
#fill in whats missing to get  print:
#[[ 1  2  3  4  5]
# [ 6  7  8  9 10]]
#shape of array : (2, 5)
#2
#5

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
shape of array : (2, 5)
2
5


In [ ]:
#תרגיל 5
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)
print('shape of array :', arr.shape)
print(arr.shape[0])
print(arr.shape[1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
shape of array : (2, 5)
2
5


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])

newarr = #fill in whats missing to get print:
#[[1 2 3]
# [4 5 6]
# [7 8 9]]

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#תרגיל 6
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])

newarr = arr.reshape(3,3)


print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

#fill in whats missing to get  print:
#1
#2
#3
#4
#5
#6
#7
#8
#9
#10
#11
#12

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#תרגיל 7
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
 for y in x:
  for z in y:
   print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

#fill in whats missing to get  print:
#(array([3, 5, 6], dtype=int64),)

print(x)

(array([3, 5, 6], dtype=int64),)


In [ ]:
#תרגיל 8
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr==4)

print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

#fill in whats missing to get  print:
#(array([1, 3, 5, 7], dtype=int64),)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [ ]:
#תרגיל 9
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [ ]:
import numpy as np

arr = np.array([3, 2, 0, 1])

#fill in whats missing to get below print:
#[0 1 2 3]

[0 1 2 3]


In [ ]:
#תרגיל 10
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [ ]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = #fill in whats missing to get below print

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
#תרגיל 11
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print (arr)


print (arr.shape)

print (arr.shape[0])
print (arr.shape[1])

newarr = #fill in whats missing to get below print

print(newarr)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
4
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#תרגיל 12
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print (arr)


print (arr.shape)

print (arr.shape[0])
print (arr.shape[1])

newarr = arr.reshape(4,2)

print(newarr)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
4
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr=[["avi",90],["benny",80]]

np_arr=np.array(arr)

columnIndex = 1
# Sort 2D numpy array by 2nd Column
sortedArr = np_arr[np_arr[:,columnIndex].argsort()]

print (np_arr)

print ("--------------")

print (sortedArr)


[['avi' '90']
 ['benny' '80']]
--------------
[['benny' '80']
 ['avi' '90']]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])


print (np.argmax(arr))

print (arr[np.argmax(arr)])

7
8


In [ ]:
arr = np.array([96, 24, 55, 99, 45, 78, 84, 83,79,98])

sorted_arr= np.sort(arr)

print ("two best scores are ",#fill in whats missing to get below print)

print ("two worst scores are ",#fill in whats missing to get below print)

print (arr.shape)

#this is the print we want:
#two worst scores are  24 45
#two best scores are  98 99
#(10,)

two best scores are  24 45
two worst scores are  98 99
(10,)


In [ ]:
#תרגיל 13
import numpy as np
arr = np.array([96, 24, 55, 99, 45, 78, 84, 83,79,98])

sorted_arr= np.sort(arr)

print ("two best scores are ",sorted_arr[0:2])

print ("two worst scores are ",sorted_arr[-2:])

print (arr.shape)

#this is the print we want:
#two worst scores are  24 45
#two best scores are  98 99
#(10,)

two best scores are  [24 45]
two worst scores are  [98 99]
(10,)


In [ ]:
a = np.array(42)
x=np.array([[1,2],[1,1]])
y=np.array([2,2])
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [ ]:
#תרגיל 14
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])

result = a * b

print(result)

[ 42  84 126 168 210]


In [ ]:
#תרגיל 15


[[6 4]
 [6 4]
 [6 4]]


In [ ]:
x=np.array([2,1])
y=np.array([[1,1],[1,1],[1,1]])

#fill in whats missing to get below print:
#[2 1]
#[2 1]
#[[1 1]
# [1 1]
# [1 1]]
#[[1 1 1]
# [1 1 1]]

print (x)
print (xt)
print(y)
print(y.transpose())

[2 1]
[2 1]
[[1 1]
 [1 1]
 [1 1]]
[[1 1 1]
 [1 1 1]]


In [ ]:
#תרגיל 16
import numpy as np
x=np.array([2,1])
y=np.array([[1,1],[1,1],[1,1]])

xt = x.transpose()

print (x)
print (xt)
print(y)
print(y.transpose())

[2 1]
[2 1]
[[1 1]
 [1 1]
 [1 1]]
[[1 1 1]
 [1 1 1]]
